# Generated by Django 4.2.7

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed')], max_length=20)),
                ('lead', models.CharField(max_length=255)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-lastUpdated'],
            },
        ),
    ] 